on:
  pull_request: 
        types:
         - opened

jobs:
  pr-action:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: Post PR Comment
      uses: sidd-harth-7/docker-action-pr-giphy-comment@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        giphy-api-key: ${{ secrets.GIPHY_API_KEY }}

    - name: Post Javascript Action PR Comment
      uses: sidd-harth-7/js-action-pr-giphy-comment@1.0.0-alpha
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        giphy-api-key: ${{ secrets.GIPHY_API_KEY }} 
        
